/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package _billing

import _billing.strategy.AffiliateDiscountStrategy
import _billing.strategy.EmployeeDiscountStrategy
import _billing.strategy.LoyalCustomerStrategy
import _billing.strategy.TotalBillingDiscountStrategy

fun main(args: Array<String>) {
    println("no 3, will do test cases here")

    val customerBilly = Customer(CustomerType.EMPLOYEE, 10)
    val customerSyamsul = Customer(CustomerType.GENERAL, 4)
    val customerKura = Customer( CustomerType.AFFILIATE, 4)
    val listDiscount = listOf(AffiliateDiscountStrategy(), EmployeeDiscountStrategy(),
            LoyalCustomerStrategy(), TotalBillingDiscountStrategy())
    val cashier = CashierImpl(listDiscount)
    println("once upun a time we have customer")
    println("Billy:" + customerBilly)
    println("Syamsul:"+customerSyamsul)
    println("Kura:"+customerKura)


    println("they decided to bought same thing at the same time")
    val bill = Bill( listOf(BillingItem(ProductType.GROCERIES, 500.0),
            BillingItem(ProductType.NON_GROCERIES,1000.0)))
    bill.item.forEach {
        println(it)
    }
    println("total cost without discount "+ bill.item.sumByDouble { it.cost })

    println("=======")
    println("so they goes to the cashier")
    println("payment for Billy "+customerBilly)
    println("Billy pays: "+ cashier.getTotalAmount(customerBilly, bill))
    println("-----")
    println("payment for Syamsul "+customerSyamsul)
    println("Syamsul pays: "+ cashier.getTotalAmount(customerSyamsul, bill))
    println("-----")
    println("payment for Kura "+customerKura)
    println("Kura pays: "+ cashier.getTotalAmount(customerKura, bill))
}
