/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package _mapText

fun main(args: Array<String>) {
    val parser = StringParserImpl()
    val representationParser = RepresentationParserImpl()
    val factory = ArrayMapFactoryImpl(parser,representationParser)

    println("==== HELLO question no 1 ======")
    val testString = "run=lari;jump=loncat\nlari=run;loncat=run"
    println("we will try from this string first:${testString.escape()}")
    val input = testString
    println("")

    try{
        val data = factory.generateFromString(input)
        println("inputed string:${input.escape()}")
        println("we will input another for you")
        val anotherMap = factory.create(1)
        anotherMap[0].put("hello","hi")
        anotherMap[0].put("hi","hello")
        println("map we've inserted :${anotherMap[0].getRepresentation()}")
        val combine = data + anotherMap
        println("result combine:${factory.save(combine).escape()}")
    }catch(exception:Exception){
        println("string value you've inserted is wrong, please run the program again")
    }



}


fun String.escape():String{
    return this.replace("\n","\\n")
}
